[package]
name = "sam-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
burn.workspace = true
burn-ndarray.workspace = true
burn-wgpu.workspace = true
image = "0.25.8"
ndarray = "0.16.1"
# onnxruntime = { git = "https://github.com/karelnagel/onnxruntime-rs" }
pyo3 = { version = "0.26.0", features = ["auto-initialize"] }
serde = { version = "1.0.200", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
tempfile = "3.14.0"
