[package]
name = "sam-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
burn.workspace = true
burn-ndarray.workspace = true
burn-wgpu.workspace = true
image = "0.25.8"
md-5 = "0.10.6"
ndarray = "0.16.1"
# onnxruntime = { git = "https://github.com/karelnagel/onnxruntime-rs" }
opencv = "0.96.0"
pyo3 = { version = "0.26.0", features = ["auto-initialize"] }
regex = "1.10.4"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.114"
simd-json = "0.17.0"
# tch = "0.19.0"  # Replaced with WGPU backend
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
