[package]
name = "sam-convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sam-rs = { path = "../sam-rs", features = ["pyo3"] }
burn-ndarray.workspace = true
burn.workspace = true
pyo3 = { version = "0.26.0", features = ["auto-initialize"] }
serde = "1.0.200"
regex = "1.10.4"

[profile.release]
strip = true
